DROP TABLE IF EXISTS CREDIT_CARD_INFO;  

CREATE TABLE CREDIT_CARD_INFO (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,  
	NAME VARCHAR(50) NOT NULL,  
	CARD_NUMBER BIGINT NOT NULL,
	LIMITS BIGINT NOT NULL,
	BALANCE DOUBLE NOT NULL
);  